create table if not exists public.gallery_posts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 40),
  caption text not null check (char_length(caption) between 1 and 280),
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.gallery_posts enable row level security;

drop policy if exists "Lectura pública de galería" on public.gallery_posts;
create policy "Lectura pública de galería"
on public.gallery_posts for select
to anon, authenticated
using (true);

drop policy if exists "Publicación de galería" on public.gallery_posts;
create policy "Publicación de galería"
on public.gallery_posts for insert
to anon, authenticated
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'gallery_posts'
  ) then
    alter publication supabase_realtime add table public.gallery_posts;
  end if;
end
$$;

insert into storage.buckets (id, name, public)
values ('gallery-images', 'gallery-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Lectura pública de imágenes de galería" on storage.objects;
create policy "Lectura pública de imágenes de galería"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'gallery-images');

drop policy if exists "Carga pública de imágenes de galería" on storage.objects;
create policy "Carga pública de imágenes de galería"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'gallery-images');
