create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 40),
  rating integer not null check (rating between 1 and 5),
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

drop policy if exists "Lectura pública de reseñas" on public.reviews;
create policy "Lectura pública de reseñas"
on public.reviews for select
to anon, authenticated
using (true);

drop policy if exists "Publicación pública de reseñas" on public.reviews;
create policy "Publicación pública de reseñas"
on public.reviews for insert
to anon, authenticated
with check (true);

